version: "3.8"
services:
  db:
    image: mysql:8.0
    container_name: hotel_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: HOTEL_MANAGEMENT
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./src/config/database.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data: